version: "3.2"
services:
  microservice:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    image: microservice
    container_name: microservice
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - redis
    networks:
      - microservice_net
    environment:
      REDIS_HOST: "redis"

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - 6379:6379
    networks:
      - microservice_net

networks:
  microservice_net:
    driver: bridge
